public class LocalCouncillorWrapper {
   public   Id  SqlId   {get;set;}
    public  String  CouncilName {get;set;}
    public  String  CouncilType {get;set;}
    public  String  CouncilRegion   {get;set;}
    public  String  Name    {get;set;}
    public  String  Title   {get;set;}
    public  String  Party   {get;set;}
    public  String  Ward    {get;set;}
    public  String  HomeAddress {get;set;}
    public  String  PhoneNumber {get;set;}
    public  String  MobileNumber    {get;set;}
    public  String  Email   {get;set;}
    public  String  CommiteeAppointments    {get;set;}
    public  String  Twitter {get;set;}
    public  String  OutsideAppointments {get;set;}
    public  String  TermofOffice    {get;set;}
    public  String  URL {get;set;}

    public LocalCouncillorWrapper(){
        
    }

}